/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.servidor.igrafica;

import com.mxrck.autocompleter.TextAutoCompleter;
import com.soltelec.servidor.dao.ClasesVehiculoJpaController;
import com.soltelec.servidor.dao.LineasVehiculosJpaController;
import com.soltelec.servidor.dao.MarcasJpaController;
import com.soltelec.servidor.dao.ServiciosJpaController;
import com.soltelec.servidor.dao.TipoVehiculoJpaController;
import com.soltelec.servidor.model.ClasesVehiculo;
import com.soltelec.servidor.model.Datos;
import com.soltelec.servidor.model.LineasVehiculos;
import com.soltelec.servidor.model.Marcas;
import com.soltelec.servidor.model.ParametrosBusqueda;
import com.soltelec.servidor.model.Servicios;
import com.soltelec.servidor.model.TipoVehiculo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CriteriosBusqueda extends javax.swing.JDialog {

    private TextAutoCompleter textAutoAcompleterTipo;
    private TextAutoCompleter textAutoAcompleterMarca;
    private TextAutoCompleter textAutoAcompletercClase;
    private TextAutoCompleter textAutoAcompleterServicio;
    private TextAutoCompleter textAutoAcompleterLinea;
    private InternalPruebaVisual pruebaVisual;

    /**
     * Creates new form CriteriosBusqueda
     *
     * @param pruebaVisual
     */
    public CriteriosBusqueda(InternalPruebaVisual pruebaVisual) {
        initComponents();
        cmbEstado.setSelectedIndex(-1);
        //cmbEstado.removeItemAt(0);
        cargarLista();
        this.pruebaVisual = pruebaVisual;

    }

    public CriteriosBusqueda() {
        initComponents();
        cmbEstado.setSelectedIndex(-1);
        //cmbEstado.removeItemAt(0);
        cargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        cmbCilindraje = new javax.swing.JComboBox();
        cmbModelo = new javax.swing.JComboBox();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        txtNumeroMotor = new javax.swing.JTextField();
        txtVin = new javax.swing.JTextField();
        txtNumeroLicencia = new javax.swing.JTextField();
        txtNumeroEjes = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtClase = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        txtIdPropietario = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);

        jLabel9.setBackground(java.awt.Color.lightGray);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Servicio:");
        jLabel9.setOpaque(true);

        cmbCilindraje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", "<", ">" }));

        cmbModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", "<", ">" }));

        txtMarca.setToolTipText("");

        txtTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoFocusGained(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setBackground(java.awt.Color.lightGray);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Nùmero de ejes:");
        jLabel17.setOpaque(true);

        jLabel18.setBackground(java.awt.Color.lightGray);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Marca:");
        jLabel18.setOpaque(true);

        jLabel19.setBackground(java.awt.Color.lightGray);
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tipo Vehiculo:");
        jLabel19.setOpaque(true);

        jLabel20.setBackground(java.awt.Color.lightGray);
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cilindraje:");
        jLabel20.setOpaque(true);

        jLabel21.setBackground(java.awt.Color.lightGray);
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Clase Vehiculo:");
        jLabel21.setOpaque(true);

        jLabel22.setBackground(java.awt.Color.lightGray);
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Linea Vehiculo:");
        jLabel22.setOpaque(true);

        jLabel23.setBackground(java.awt.Color.lightGray);
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Placa:");
        jLabel23.setOpaque(true);

        jLabel24.setBackground(java.awt.Color.lightGray);
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Modelo:");
        jLabel24.setOpaque(true);

        jLabel25.setBackground(java.awt.Color.lightGray);
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Marca:");
        jLabel25.setOpaque(true);

        jLabel26.setBackground(java.awt.Color.lightGray);
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Numero Motor:");
        jLabel26.setOpaque(true);

        jLabel27.setBackground(java.awt.Color.lightGray);
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("VIN:");
        jLabel27.setOpaque(true);

        jLabel28.setBackground(java.awt.Color.lightGray);
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Identificacòn Propietario:");
        jLabel28.setOpaque(true);

        jLabel29.setBackground(java.awt.Color.lightGray);
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Apellido Propietario:");
        jLabel29.setOpaque(true);

        jLabel30.setBackground(java.awt.Color.lightGray);
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Nombre Propietario:");
        jLabel30.setOpaque(true);

        jLabel32.setBackground(java.awt.Color.lightGray);
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Nùmero de licencia:");
        jLabel32.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Busqueda Avanzada");

        jLabel31.setBackground(java.awt.Color.lightGray);
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Estado");
        jLabel31.setOpaque(true);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "APROBADA", "REPROBADA", "PENDIENTE" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtClase, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNumeroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtNumeroEjes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIdPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNumeroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNumeroEjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusGained

    }//GEN-LAST:event_txtTipoFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Integer d;
        ParametrosBusqueda busqueda = new ParametrosBusqueda();
        busqueda.setApellido(txtApellido.getText());

        if (!txtCilindraje.getText().isEmpty()) {
            busqueda.setCmbcilindraje(cmbCilindraje.getSelectedItem().toString());
            busqueda.setCilindraje(Integer.parseInt(txtCilindraje.getText()));
        } else {
            busqueda.setCilindraje(0);
        }
        if (textAutoAcompletercClase.getItemSelected() != null && !txtClase.getText().isEmpty()) {
            Datos datosClase = ((Datos) textAutoAcompletercClase.findItem(txtClase.getText()));
            if (!datosClase.getNombre().isEmpty() && datosClase.getId() > 0) {
                busqueda.setClase(datosClase.getId());
            }
        } else {
            busqueda.setClase(0);
        }
        if (textAutoAcompleterLinea.getItemSelected() != null && !txtLinea.getText().isEmpty()) {
            Datos dd = ((Datos) textAutoAcompleterLinea.findItem(txtLinea.getText()));
            if (!dd.getNombre().isEmpty() && dd.getId() > 0) {
                busqueda.setLinea(dd.getId());
            }
        } else {
            busqueda.setLinea(0);
        }
        if (textAutoAcompleterMarca.getItemSelected() != null && !txtMarca.getText().isEmpty()) {
            Datos datosMarca = ((Datos) textAutoAcompleterMarca.findItem(txtMarca.getText()));
            if (!datosMarca.getNombre().isEmpty() && datosMarca.getId() > 0) {
                busqueda.setMarca(datosMarca.getId());
            }
        } else {
            busqueda.setMarca(0);
        }
        if (!txtModelo.getText().isEmpty()) {
            busqueda.setCmbModelo(cmbModelo.getSelectedItem().toString());
            busqueda.setModelo(Integer.parseInt(txtModelo.getText()));
        }
        if (!txtCilindraje.getText().isEmpty()) {
            busqueda.setCmbModelo(cmbModelo.getSelectedItem().toString());
            busqueda.setCilindraje(Integer.parseInt(txtCilindraje.getText()));
        }
        busqueda.setNombre(txtNombres.getText());
        if (!txtNumeroEjes.getText().isEmpty()) {
            busqueda.setNumeroEjes(Integer.parseInt(txtNumeroEjes.getText()));
        }
        busqueda.setNumeroLicencia(txtNumeroLicencia.getText());
        busqueda.setNumeroMotor(txtNumeroMotor.getText());
        busqueda.setPlaca(txtPlaca.getText());
        //Servicio
        if (textAutoAcompleterServicio.getItemSelected() != null && !txtServicio.getText().isEmpty()) {
            Datos datosServicio = ((Datos) textAutoAcompleterServicio.findItem(txtServicio.getText()));
            if (!datosServicio.getNombre().isEmpty() && datosServicio.getId() > 0) {
                busqueda.setServicio(datosServicio.getId());
            }
        } else {
            busqueda.setServicio(0);
        }
        if (textAutoAcompleterTipo.getItemSelected() != null && !txtTipo.getText().isEmpty()) {
            Datos datosTipo = ((Datos) textAutoAcompleterTipo.findItem(txtTipo.getText()));
            if (!datosTipo.getNombre().isEmpty() && datosTipo.getId() > 0) {
                busqueda.setTipo(datosTipo.getId());
            }
        } else {
            busqueda.setTipo(0);
        }
        busqueda.setVin(txtVin.getText());

        if (!txtNumeroEjes.getText().isEmpty()) {
            busqueda.setNumeroEjes(Integer.parseInt(txtNumeroEjes.getText()));
        }

        busqueda.setNumeroLicencia(txtNumeroLicencia.getText());

        if (!txtIdPropietario.getText().isEmpty()) {
            busqueda.setIdPropietario(Long.parseLong(txtIdPropietario.getText()));
        }

        busqueda.setNumeroMotor(txtNumeroMotor.getText());

        busqueda.setPlaca(txtPlaca.getText());
        if (cmbEstado.getSelectedItem() == null) {
            busqueda.setEstado("");
        } else {
            busqueda.setEstado(cmbEstado.getSelectedItem().toString());
        }

        StringBuilder sb = new StringBuilder();
        if (validarCampos(busqueda.getApellido(), busqueda.getNombre(), busqueda.getNumeroLicencia())) {
            sb.append("select hp.* from vehiculos v INNER join hoja_pruebas hp ON v.CAR=hp.Vehiculo_for inner join propietarios p on v.`CAROWNER` = p.`CAROWNER` where v.`CAR` = v.`CAR` ");
        } else {
            sb.append("select hp.* from vehiculos v INNER join hoja_pruebas hp ON v.CAR=hp.Vehiculo_for where v.`CAR` = v.`CAR` ");
        }
        if (validarCampos(busqueda.getNombre())) {
            sb.append("and p.`Nombres` like '%").append(busqueda.getNombre()).append("%' ");
        }

        if (validarCampos(busqueda.getApellido())) {
            sb.append("and p.`Apellidos` like '%").append(busqueda.getApellido()).append("%' ");
        }
        if (validarCampos(busqueda.getNumeroLicencia())) {
            sb.append("and p.`Numero_licencia` like '%").append(busqueda.getNumeroLicencia()).append("%' ");
        }
        if ((busqueda.getNumeroEjes()) > 0) {
            sb.append("and v.`Numero_ejes` like '%").append(busqueda.getNumeroEjes()).append("%' ");
        }
        if (busqueda.getCilindraje() > 0) {
            sb.append("and v.`Cinlindraje`").append(busqueda.getCmbcilindraje()).append(busqueda.getCilindraje()).append(" ");
        }
        if (busqueda.getModelo() > 0) {
            sb.append("and v.`Modelo` ").append(busqueda.getCmbModelo()).append(busqueda.getModelo()).append(" ");
        }

        if (validarCampos(busqueda.getNumeroLicencia())) {
            sb.append("and p.`Numero_licencia` like '%").append(busqueda.getNumeroLicencia()).append("%' ");
        }
        if (validarCampos(busqueda.getPlaca())) {
            sb.append("and v.`CARPLATE` like '%").append(busqueda.getPlaca()).append("%' ");
        }
        if (validarCampos(busqueda.getEstado()) && !busqueda.getEstado().equals(" ")) {

            sb.append("and hp.`estado` = '").append(busqueda.getEstado()).append("' ");
        }
//        if (dteFechaFinal.getDate() != null || dteFechaInicial.getDate() != null) {
////            if (dteFechaFinal.getDate() == null || dteFechaInicial.getDate() == null) {
////                Mensajes.mensajeAdvertencia("Debe seleccionar las dos fechas");
////            }
//            SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
//            sb.append("and hp.Fecha_ingreso_vehiculo between '").append(formateador.format(dteFechaInicial.getDate())).append("' and '").append(formateador.format(dteFechaFinal.getDate())).append("' ");
//        }
        if (validarCampos(busqueda.getNumeroMotor())) {
            sb.append("and v.`Numero_motor` like '%").append(busqueda.getNumeroMotor()).append("%' ");
        }
        if (busqueda.getIdPropietario() > 0) {
            sb.append("and p.`CAROWNER` like '%").append(busqueda.getIdPropietario()).append("%' ");
        }
        if (busqueda.getServicio() > 0) {
            sb.append(String.format("and v.`SERVICE` = %d ", busqueda.getServicio()));
        }

        if (busqueda.getLinea() > 0) {
            sb.append(String.format("and v.`CARLINE` = %d ", busqueda.getLinea()));
        }
        if (busqueda.getClase() > 0) {
            sb.append(String.format("and v.`CLASS` = %d ", busqueda.getClase()));
        }
        if (busqueda.getMarca() > 0) {
            sb.append(String.format("and v.`CARMARK` = %d ", busqueda.getMarca()));
        }
        if (busqueda.getTipo() > 0) {
            sb.append(String.format("and v.`CARTYPE` = %d ", busqueda.getTipo()));
        }

        if (sb.toString().equals("select hp.* from vehiculos v INNER join hoja_pruebas hp ON v.CAR=hp.Vehiculo_for where v.`CAR` = v.`CAR` ")) {
            JOptionPane.showMessageDialog(this, "Seleccione un parametro");
            return;
        }
        System.out.println(sb);
        pruebaVisual.cargarHojas(sb.toString());
//        HojaPruebasJpaController controller = new HojaPruebasJpaController();
//        List<HojaPruebas> h = controller.BuscarCriterios(sb.toString());
//        for (HojaPruebas hojaPruebas : h) {
//            System.out.println(hojaPruebas);
//        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean validarCampos(String... arg) {
        for (String string : arg) {
            if (string != null && !string.isEmpty()) {
                return true;
            }
        }
        return false;
    }

    private void cargarLista() {
        textAutoAcompleterTipo = new TextAutoCompleter(txtTipo);
        textAutoAcompleterTipo.setMode(0);
        TipoVehiculoJpaController jpaControllerTipo = new TipoVehiculoJpaController();
        List<TipoVehiculo> listTipo = jpaControllerTipo.findVehiculo1();
        List<Datos> datosTipo = new ArrayList<Datos>();
        for (TipoVehiculo v : listTipo) {
            datosTipo.add(new Datos(v.getCartype(), v.getNombre()));
        }
        textAutoAcompleterTipo.addItems(datosTipo.toArray());

        textAutoAcompleterMarca = new TextAutoCompleter(txtMarca);
        textAutoAcompleterMarca.setMode(0);
        MarcasJpaController jpaControllerMarca = new MarcasJpaController();
        Marcas marca = new Marcas();
        List<Datos> datosMarca = new ArrayList<Datos>();
        List<Marcas> listMarca = jpaControllerMarca.findAll();
        for (Marcas M : listMarca) {
            datosMarca.add(new Datos(M.getCarmark(), M.getNombremarca()));
        }
        textAutoAcompleterMarca.addItems(datosMarca.toArray());

        textAutoAcompletercClase = new TextAutoCompleter(txtClase);
        textAutoAcompletercClase.setMode(0);
        ClasesVehiculoJpaController jpaControllerClase = new ClasesVehiculoJpaController();
        List<Datos> datosClase = new ArrayList<Datos>();
        List<ClasesVehiculo> listClaseVehiculo = jpaControllerClase.findAll();
        for (ClasesVehiculo C : listClaseVehiculo) {
            datosClase.add(new Datos(C.getClass1(), C.getNombreclase()));
        }
        textAutoAcompletercClase.addItems(datosClase.toArray());

        textAutoAcompleterServicio = new TextAutoCompleter(txtServicio);
        textAutoAcompleterServicio.setMode(0);
        ServiciosJpaController jpaControllerServicio = new ServiciosJpaController();
        Servicios servicio = new Servicios();
        List<Datos> datosServicio = new ArrayList<Datos>();
        List<Servicios> listClaseServicio = jpaControllerServicio.findAll();
        for (Servicios s : listClaseServicio) {
            datosServicio.add(new Datos(s.getService(), s.getNombreservicio()));
        }
        textAutoAcompleterServicio.addItems(datosServicio.toArray());

        textAutoAcompleterLinea = new TextAutoCompleter(txtLinea);
        textAutoAcompleterLinea.setMode(0);
        LineasVehiculosJpaController jpaControllerLinea = new LineasVehiculosJpaController();
        LineasVehiculos lineavehiculo = new LineasVehiculos();
        List<Datos> datosLineae = new ArrayList<Datos>();
        List<LineasVehiculos> listClaseLinea = jpaControllerLinea.findAll();
        for (LineasVehiculos l : listClaseLinea) {
            datosLineae.add(new Datos(l.getCarline(), l.getCrlname()));
        }
        textAutoAcompleterLinea.addItems(datosLineae.toArray());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriteriosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriteriosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriteriosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriteriosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriteriosBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCilindraje;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbModelo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtClase;
    private javax.swing.JTextField txtIdPropietario;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroEjes;
    private javax.swing.JTextField txtNumeroLicencia;
    private javax.swing.JTextField txtNumeroMotor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtVin;
    // End of variables declaration//GEN-END:variables
}
