package com.soltelec.servidor.igrafica;

import com.soltelec.servidor.dao.EquiposJpaController;
import com.soltelec.servidor.dao.exceptions.IllegalOrphanException;
import com.soltelec.servidor.dao.exceptions.NonexistentEntityException;
import com.soltelec.servidor.dao.exceptions.PreexistingEntityException;
import com.soltelec.servidor.utils.CMensajes;
import com.soltelec.servidor.utils.CValidaciones;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SOLTELEC
 */
public class Equipos extends javax.swing.JInternalFrame {

    DefaultTableModel tableModeloEquipos;
    com.soltelec.servidor.model.Equipos equipoGlobal;
    List<com.soltelec.servidor.model.Equipos> listaEquipos;
    Integer idEquipo;
    private boolean editando;
    EquiposJpaController controller;
    private boolean userCorrecto;

    /**
     * Creates new form FrInt1
     */
    public Equipos() {
        super("Equipos",
                true, //resizable
                true, //closable
                false, //maximizable
                true);

        initComponents();
        btnNuevo.setEnabled(false);
        dlgEquipos.setSize(380, 280);
        tableModeloEquipos = new DefaultTableModel();
        tableModeloEquipos.addColumn("Id");
        tableModeloEquipos.addColumn("Serial");
        tableModeloEquipos.addColumn("PEF");
        tableModeloEquipos.addColumn("Marca");
        tableModeloEquipos.addColumn("# Analizador");
        tblEquipos.setModel(tableModeloEquipos);
        controller = new EquiposJpaController();
        listaEquipos = controller.buscarEquipos("");
        listarEquipos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgEquipos = new javax.swing.JDialog();
        pnlEquipo = new javax.swing.JPanel();
        txtSerial = new javax.swing.JTextField();
        lblSerial = new javax.swing.JLabel();
        txtPEF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardarEquipo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblSerialValidator = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtNumAnalizador = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEquipos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarEquipos = new javax.swing.JTextField();

        dlgEquipos.setMinimumSize(new java.awt.Dimension(400, 420));

        pnlEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Equipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        txtSerial.setToolTipText("");
        txtSerial.setName("Serial"); // NOI18N
        txtSerial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSerialFocusLost(evt);
            }
        });

        lblSerial.setText("Serial:");

        txtPEF.setName("PEF"); // NOI18N

        jLabel3.setText("PEF:");

        jLabel6.setText("Marca:");

        btnGuardarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/accept.png"))); // NOI18N
        btnGuardarEquipo.setText("Aceptar");
        btnGuardarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEquipoActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/block.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Num. Analizador:");

        lblSerialValidator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtMarca.setName("Marca"); // NOI18N

        txtNumAnalizador.setName("Num. Analizador"); // NOI18N

        javax.swing.GroupLayout pnlEquipoLayout = new javax.swing.GroupLayout(pnlEquipo);
        pnlEquipo.setLayout(pnlEquipoLayout);
        pnlEquipoLayout.setHorizontalGroup(
            pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEquipoLayout.createSequentialGroup()
                        .addComponent(btnGuardarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(pnlEquipoLayout.createSequentialGroup()
                        .addGroup(pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(lblSerial)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPEF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumAnalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSerialValidator, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEquipoLayout.setVerticalGroup(
            pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSerial)
                        .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSerialValidator, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPEF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumAnalizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtSerial.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout dlgEquiposLayout = new javax.swing.GroupLayout(dlgEquipos.getContentPane());
        dlgEquipos.getContentPane().setLayout(dlgEquiposLayout);
        dlgEquiposLayout.setHorizontalGroup(
            dlgEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgEquiposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgEquiposLayout.setVerticalGroup(
            dlgEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgEquiposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setClosable(true);
        setResizable(true);
        setTitle("Manejo de equipos");
        setFrameIcon(null);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/new.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/edit.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/delete.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipos"));

        tblEquipos.setModel(new DefaultTableModel());
        tblEquipos.setToolTipText("Listado de usuarios");
        tblEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEquiposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEquipos);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/search.png"))); // NOI18N
        jLabel1.setToolTipText("Para realizar una busqueda escriba en la caja de texto y de enter");

        txtBuscarEquipos.setToolTipText("Busqueda de usuarios");
        txtBuscarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarEquipos)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBuscarEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCampos();
        editando = false;
        txtSerial.setEnabled(true);
        dlgEquipos.setVisible(true);
        dlgEquipos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtBuscarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarEquiposActionPerformed
        String parametro = txtBuscarEquipos.getText();
        listaEquipos = controller.buscarEquipos(parametro);
        listarEquipos();
    }//GEN-LAST:event_txtBuscarEquiposActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        limpiarCampos();
        cargarIdEquipo();
        equipoGlobal = controller.findEquipos(idEquipo);
        
        txtSerial.setText(equipoGlobal.getSerial());        
        txtPEF.setText(String.valueOf(equipoGlobal.getPef()));
        txtMarca.setText(equipoGlobal.getMarca());
        txtNumAnalizador.setText(equipoGlobal.getNumAnalizador());
        
        txtSerial.setEnabled(false);        
        editando = true;
        
        dlgEquipos.setVisible(true);
        dlgEquipos.setLocationRelativeTo(null);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!CMensajes.mensajePregunta("Seguro que desea eliminar este equipo?")) {
            return;
        }
        cargarIdEquipo();
        try {
            com.soltelec.servidor.model.Equipos equipo = controller.findEquipos(idEquipo);
            
            if (!equipo.getCalibracionesList().isEmpty()) {
                CMensajes.mensajeError("No se elimino el equipo con Id " + idEquipo + " ya que tiene calibraciones registradas");
                return;
            }
            
            controller.destroy(idEquipo);
            CMensajes.mensajeCorrecto("Se elimino el equipo con Id " + idEquipo);
            txtBuscarEquiposActionPerformed(evt);
        } catch (IllegalOrphanException | NonexistentEntityException | HeadlessException ex) {
            CMensajes.mostrarExcepcion(ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEquiposMouseClicked
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_tblEquiposMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dlgEquipos.setVisible(false);
        lblSerialValidator.setIcon(null);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEquipoActionPerformed

        if (!CValidaciones.validarCampos(pnlEquipo)) {
            return;
        }
        
        if (editando) {
            try {
                equipoGlobal.setSerial(txtSerial.getText());
                equipoGlobal.setPef(Integer.parseInt(txtPEF.getText()));
                equipoGlobal.setMarca(txtMarca.getText());
                equipoGlobal.setNumAnalizador(txtNumAnalizador.getText());
                controller.edit(equipoGlobal);
                JOptionPane.showMessageDialog(this, "Se actualizo la infomación");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se guardo la infomación " + ex);
            }
        } else {
            try {
                if (!userCorrecto) {
                    CMensajes.mensajeError("Ya existe el equipo con Serial " + txtSerial.getText());
                    return;
                }
                
                equipoGlobal = new com.soltelec.servidor.model.Equipos();
                equipoGlobal.setSerial(txtSerial.getText());
                equipoGlobal.setPef(Integer.parseInt(txtPEF.getText()));
                equipoGlobal.setMarca(txtMarca.getText());
                equipoGlobal.setNumAnalizador(txtNumAnalizador.getText());
                controller.create(equipoGlobal);
                CMensajes.mensajeCorrecto("Se guardo la informacion");
            } catch (NumberFormatException | PreexistingEntityException ex) {
                CMensajes.mostrarExcepcion(ex);
            }
        }
        dlgEquipos.setVisible(false);
        lblSerialValidator.setIcon(null);
        txtBuscarEquiposActionPerformed(evt);
    }//GEN-LAST:event_btnGuardarEquipoActionPerformed

    private void txtSerialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSerialFocusLost
        controller = new EquiposJpaController();
        if (!txtSerial.getText().equals("")) {
            if (controller.isRegistrado(txtSerial.getText())) {
                lblSerialValidator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/block.png")));
                userCorrecto = false;
            } else {
                lblSerialValidator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/accept.png")));
                userCorrecto = true;
            }
        } else {
            lblSerialValidator.setIcon(null);
        }
    }//GEN-LAST:event_txtSerialFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarEquipo;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JDialog dlgEquipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblSerialValidator;
    private javax.swing.JPanel pnlEquipo;
    private javax.swing.JTable tblEquipos;
    private javax.swing.JTextField txtBuscarEquipos;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNumAnalizador;
    private javax.swing.JTextField txtPEF;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        txtPEF.setText(null);
        txtMarca.setText(null);
        txtSerial.setText(null);
        txtNumAnalizador.setText(null);
        txtSerial.setText(null);
    }

    private void listarEquipos() {
        Object[] fila;
        if (!listaEquipos.isEmpty()) {
            tableModeloEquipos = new DefaultTableModel();
            tableModeloEquipos.addColumn("Id");
            tableModeloEquipos.addColumn("Serial");
            tableModeloEquipos.addColumn("PEF");
            tableModeloEquipos.addColumn("Marca");
            tableModeloEquipos.addColumn("# Analizador");
            for (com.soltelec.servidor.model.Equipos equipos : listaEquipos) {
                fila = new Object[5];
                fila[0] = equipos.getIdEquipo();
                fila[1] = equipos.getReolucionserial();
                fila[2] = "0,"+equipos.getPef();
                fila[3] = equipos.getMarca();
                fila[4] = equipos.getNumAnalizador();
                tableModeloEquipos.addRow(fila);
            }
            tblEquipos.setModel(tableModeloEquipos);
        }
    }

    private void cargarIdEquipo() {
        idEquipo = Integer.parseInt(String.valueOf(tableModeloEquipos.getValueAt(tblEquipos.getSelectedRow(), 0)));
    }
}
