/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrInt1.java
 *
 * Created on 30/06/2011, 11:05:09 AM
 */
package com.soltelec.servidor.igrafica;

import com.soltelec.servidor.dao.CdaJpaController;
import com.soltelec.servidor.dao.LlantasDAO;
import com.soltelec.servidor.dao.LlantasJpaController;
import com.soltelec.servidor.dao.UsuariosJpaController;
import com.soltelec.servidor.dao.exceptions.IllegalOrphanException;
import com.soltelec.servidor.model.Cda;
import com.soltelec.servidor.model.Llantas;
import com.soltelec.servidor.model.Usuarios;
import com.soltelec.servidor.utils.CMensajes;
import com.soltelec.servidor.utils.CValidaciones;
//import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author SOLTELEC
 */
public class FrmLlantas extends javax.swing.JInternalFrame {

    Llantas llantas;
    LlantasJpaController Controller;
    DefaultTableModel tableModelLlantas;
    List<Llantas> Lsllantas;
    private Date fecha;
    Integer IdEdit=0;
    private LlantasDAO ldao = new  LlantasDAO();
    private boolean passValido;
    private boolean userValido;
    private static final Logger LOG = Logger.getLogger(FrmSimulacion.class.getName());
     boolean editando = false;

    /**
     * Creates new form FrInt1
     */
    public FrmLlantas() {
        super("Llantas",
                true, //resizable
                true, //closable
                false, //maximizable
                true);

        initComponents();
        MostrarLlantas();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo_Agregar = new javax.swing.JDialog();
        frmPropiedades = new javax.swing.JPanel();
        txtNombreLlanta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_guardarLlanta = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRadioLlanta = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_llantas = new javax.swing.JTable();

        dialogo_Agregar.setMinimumSize(new java.awt.Dimension(400, 420));

        frmPropiedades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos llanta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        txtNombreLlanta.setToolTipText("");
        txtNombreLlanta.setName("Usuario"); // NOI18N
        txtNombreLlanta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreLlantaFocusLost(evt);
            }
        });

        jLabel2.setText("Nombre llanta:");

        btn_guardarLlanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/accept.png"))); // NOI18N
        btn_guardarLlanta.setText("Guardar");
        btn_guardarLlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarLlantaActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/block.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Radio llanta");

        txtRadioLlanta.setToolTipText("");
        txtRadioLlanta.setName("Usuario"); // NOI18N

        javax.swing.GroupLayout frmPropiedadesLayout = new javax.swing.GroupLayout(frmPropiedades);
        frmPropiedades.setLayout(frmPropiedadesLayout);
        frmPropiedadesLayout.setHorizontalGroup(
            frmPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmPropiedadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreLlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(frmPropiedadesLayout.createSequentialGroup()
                .addGroup(frmPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPropiedadesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRadioLlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmPropiedadesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btn_guardarLlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frmPropiedadesLayout.setVerticalGroup(
            frmPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmPropiedadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreLlanta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadioLlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(frmPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarLlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txtNombreLlanta.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout dialogo_AgregarLayout = new javax.swing.GroupLayout(dialogo_Agregar.getContentPane());
        dialogo_Agregar.getContentPane().setLayout(dialogo_AgregarLayout);
        dialogo_AgregarLayout.setHorizontalGroup(
            dialogo_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_AgregarLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(frmPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        dialogo_AgregarLayout.setVerticalGroup(
            dialogo_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_AgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frmPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setClosable(true);
        setResizable(true);
        setTitle("SICOV");
        setFrameIcon(null);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Llantas registradas"));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/add.png"))); // NOI18N
        btnNuevo.setText("agrega");
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setPreferredSize(new java.awt.Dimension(61, 51));
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/edit.png"))); // NOI18N
        btnEditar.setText("editar");
        btnEditar.setToolTipText("Nuevo");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/delete.png"))); // NOI18N
        btnEliminar.setText("eliminar");
        btnEliminar.setToolTipText("Nuevo");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tabla_llantas.setModel(new DefaultTableModel());
        tabla_llantas.setToolTipText("Listado de llantas ");
        tabla_llantas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_llantasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_llantas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar))
                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("UrlSicov");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dialogo_Agregar.setVisible(false);
       this.setVisible(true);
       
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void btn_guardarLlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarLlantaActionPerformed
        System.out.println("valor de editando: " + editando);
             
        if (editando) 
        {             
            System.out.println("se esta editando la llanta,valor del id que voy a editar: " + IdEdit);            
            JOptionPane.showMessageDialog(null, ldao.actualizarLlantas(IdEdit, txtNombreLlanta.getText(), Integer.parseInt(txtRadioLlanta.getText())));
            dialogo_Agregar.setVisible(false);
            MostrarLlantas();
            this.setVisible(true);
            txtNombreLlanta.setText("");
             txtRadioLlanta.setText("");
        } else
        {
            System.out.println("se esta agregando la llanta");
            if (ValidarCampos()) 
            {
                try 
                {
                    Integer radio = Integer.parseInt(txtRadioLlanta.getText());     
                    
                    JOptionPane.showMessageDialog(null, ldao.insertarLlantas( txtNombreLlanta.getText(), radio, Integer.BYTES));
                    txtNombreLlanta.setText("");
                    txtRadioLlanta.setText("");
                    dialogo_Agregar.setVisible(false);
                    MostrarLlantas();
                    this.setVisible(true);
                } catch (Exception e) 
                {
                    System.out.println("error al insertar la llanta " + e);
                    JOptionPane.showMessageDialog(null, "Error al intentar ingresar los datos", "ERROR", 0);
                }
            }
        }

    }//GEN-LAST:event_btn_guardarLlantaActionPerformed

    private void txtNombreLlantaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreLlantaFocusLost
       
    }//GEN-LAST:event_txtNombreLlantaFocusLost

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      editando = false;
        System.out.println("entro en nuevo, deberia ser falso : "+ editando);
        this.setVisible(false);       
        dialogo_Agregar.setVisible(true);        
       dialogo_Agregar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        editando= true;
        int select = tabla_llantas.getSelectedRow();
        if(select> -1){
        System.out.println("valor de columna editar: "+ select);
        this.setVisible(false);
        dialogo_Agregar.setVisible(true);
        txtNombreLlanta.setText(tabla_llantas.getValueAt(select, 1)+ "");
        txtRadioLlanta.setText(tabla_llantas.getValueAt(select, 2)+ "");
        IdEdit=Integer.parseInt(String.valueOf(tabla_llantas.getValueAt(select, 0)));
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione en la tabla una fila para editar", "FILA SIN SELECCIONAR", 0);
            
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
 int select = tabla_llantas.getSelectedRow(),IdEliminar;
 IdEliminar=Integer.parseInt(String.valueOf(tabla_llantas.getValueAt(select, 0)));
        try {
            ldao.eliminarLlantas(IdEliminar);
             JOptionPane.showMessageDialog(null, "Datos eliminados correctamente");
             MostrarLlantas();
            
        } catch (IllegalOrphanException ex) {
            Logger.getLogger(FrmLlantas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error al intentar ingresar los datos", "ERROR", 0);
        }
 
 
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tabla_llantasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_llantasMouseClicked
        
        /*btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);*/
        

    }//GEN-LAST:event_tabla_llantasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btn_guardarLlanta;
    private javax.swing.JDialog dialogo_Agregar;
    private javax.swing.JPanel frmPropiedades;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tabla_llantas;
    private javax.swing.JTextField txtNombreLlanta;
    private javax.swing.JTextField txtRadioLlanta;
    // End of variables declaration//GEN-END:variables

    private void MostrarLlantas()
    {
        ldao.ListaLlantas(tabla_llantas);
        
    }
    private boolean ValidarCampos()
    {
        boolean Ok= true;
        if(txtNombreLlanta.getText().equalsIgnoreCase("") || txtRadioLlanta.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null,"Recuerde que todos los campos son obligatorios");
            Ok= false;
            return Ok;
        }
        try {
            Integer.parseInt(txtRadioLlanta.getText());
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Recuerde que en el radio de la llanta solo debe ingresar valores numericos", "datos invalidos", 0);
            Ok= false; 
            return Ok;
            
        }
        return Ok;
    }
   
    
  
}

