/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrInt1.java
 *
 * Created on 30/06/2011, 11:05:09 AM
 */
package com.soltelec.servidor.igrafica;

import com.soltelec.servidor.dao.Conexion;
import com.soltelec.servidor.dao.PropietariosJpaController;
import com.soltelec.servidor.model.Propietarios;
import com.soltelec.servidor.utils.CValidaciones;
import com.soltelec.servidor.utils.Validaciones;
import java.awt.Dimension;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SOLTELEC
 */
public class FrmPropietarios extends javax.swing.JInternalFrame {

    JTable jTable1 = new javax.swing.JTable();
    JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    DefaultTableModel modelo;
    private PropietariosJpaController cJpaPropietario;
    private List<Propietarios> results;

    /**
     * Creates new form FrInt1
     */
    public FrmPropietarios() {
        super("Propietarios",
                true, //resizable
                true, //closable
                false, //maximizable
                true);

//        Conexion.cargarConexion();
        initComponents();
        dimension();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblPropietarios = new javax.swing.JTable();
        pnlConsulta = new javax.swing.JPanel();
        String[] campoStrings = {"Buscar Todos","Nro de Documento", "Nro de Licencia", "Nombres", "Apellidos"};
        cmbCampo = new javax.swing.JComboBox(campoStrings);
        txtValor = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        tblPropietarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblPropietarios);

        pnlConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Crear Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        cmbCampo.setSelectedIndex(0);

        txtValor.setMinimumSize(new java.awt.Dimension(23, 18));
        txtValor.setName("Valor"); // NOI18N
        txtValor.setPreferredSize(new java.awt.Dimension(23, 20));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/accept.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/pages.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setText("Campo de Consulta");

        jLabel3.setText("Valor");

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAceptar))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultaLayout.createSequentialGroup()
                        .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaLayout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(pnlConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dimension() {
        Dimension dim = super.getToolkit().getScreenSize();
        this.setSize(dim);
    }

    private void cargarTabla() {
        cJpaPropietario = new PropietariosJpaController();
        results = cJpaPropietario.findPropietarios1();
        cargarTabla(results);
    }

    private void cargarTabla(List<Propietarios> results) {
        modelo = new DefaultTableModel();

        // Ahora sólo hay que rellenar el DefaultTableModel con los datos del ResultSet. La forma "manual" de hacer esto es la siguiente
        // Creamos las columnas.
        modelo.addColumn("Tipo de Documento");
        modelo.addColumn("Nro de Documento");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono");
        modelo.addColumn("Tipo de Licencia");
        modelo.addColumn("Nro Licencia");

        for (Propietarios result : results) {
            // Se crea un array que será una de las filas de la tabla.
            Object[] fila = new Object[8]; // Hay tres columnas en la tabla
            // Se rellena cada posición del array con una de las columnas de la tabla en base de datos.
            fila[0] = result.getTipoIdentificacion();
            fila[1] = result.getCarowner();
            fila[2] = result.getNombres();
            fila[3] = result.getApellidos();
            fila[4] = result.getDireccion();
            fila[5] = result.getNumerotelefono();
            fila[6] = result.getTipolicencia();
            fila[7] = result.getNumerolicencia();
            // Se añade al modelo la fila completa.
            modelo.addRow(fila);
        }
        tblPropietarios.setModel(modelo);
    }

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        String dato = txtValor.getText();
        String elemento = String.valueOf(cmbCampo.getSelectedItem());
        String campo = "";
        String condicion = "=";

        cJpaPropietario = new PropietariosJpaController();

        switch (elemento) {
            case "Buscar Todos":
                cargarTabla();
                return;
            case "Nro de Documento":
                if (!Validaciones.isNumeric(dato)) {
                    JOptionPane.showMessageDialog(rootPane, "Para el Nro de Documento solo se aceptan numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                campo = "carowner";
                condicion = "=";
                break;
            case "Nro de Licencia":
                campo = "numerolicencia";
                dato += "%";
                condicion = "like";
                break;
            case "Nombres":
                campo = "nombres";
                dato += "%";
                condicion = "like";
                break;
            case "Apellidos":
                campo = "apellidos";
                dato += "%";
                condicion = "like";
                break;
        }

        if (!CValidaciones.validarCampos(pnlConsulta)) {
            return;
        }

        results = cJpaPropietario.findVehiculos_porParametros(dato, campo, condicion);
        cargarTabla(results);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtValor.setText("");
        cmbCampo.setSelectedIndex(0);
}//GEN-LAST:event_btnLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cmbCampo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JTable tblPropietarios;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
