/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrInt1.java
 *
 * Created on 30/06/2011, 11:05:09 AM
 */
package com.soltelec.servidor.igrafica;

import com.soltelec.servidor.dao.PruebasJpaController;
import com.soltelec.servidor.model.Pruebas;
import com.soltelec.servidor.utils.CMensajes;
import com.soltelec.servidor.utils.CValidaciones;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GERENCIA TIC
 */
public class FrmPruebas extends javax.swing.JInternalFrame {

    JTable jTable1 = new javax.swing.JTable();
    JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    DefaultTableModel modelo;
    private PruebasJpaController cJpaPruebas;
    private Pruebas eJpaPruebas;
    private List<Object[]> results;
    private static final Logger LOG = Logger.getLogger(FrmPruebas.class.getName());

    /**
     * Creates new form FrInt1
     */
    public FrmPruebas() {
        super("Hoja de Pruebas",
                true, //resizable
                true, //closable
                false, //maximizable
                true);
//        Conexion.cargarConexion();

        initComponents();

        dimension();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPruebas = new javax.swing.JTable();
        pnlConsulta = new javax.swing.JPanel();
        String[] campoStrings = {"Buscar Todos","Nro de Documento", "Placa","Nro de Licencia", "Nombres", "Apellidos"};
        cmbCampo = new javax.swing.JComboBox(campoStrings);
        txtValor = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);

        tblPruebas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPruebasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPruebas);

        pnlConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Crear Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        cmbCampo.setSelectedIndex(0);

        txtValor.setMinimumSize(new java.awt.Dimension(23, 18));
        txtValor.setName("Valor"); // NOI18N
        txtValor.setPreferredSize(new java.awt.Dimension(23, 20));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/accept.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/pages.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setText("Campo de Consulta");

        jLabel3.setText("Valor");

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAceptar))
                .addGap(260, 260, 260))
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultaLayout.createSequentialGroup()
                        .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaLayout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dimension() {
        Dimension dim = super.getToolkit().getScreenSize();
        this.setSize(dim);
    }

    private void cargarTabla() {
        cJpaPruebas = new PruebasJpaController();
        results = cJpaPruebas.findHojaPrueba();
        cargarTabla(results);
    }

    private void cargarTabla(List<Object[]> results) {

        modelo = new DefaultTableModel();

        // Ahora sólo hay que rellenar el DefaultTableModel con los datos del ResultSet. La forma "manual" de hacer esto es la siguiente
        // Creamos las columnas.
        modelo.addColumn("Serial");
        modelo.addColumn("Placa");
        modelo.addColumn("Propietario");
        modelo.addColumn("FIngreso");
        modelo.addColumn("FExpiración");
        modelo.addColumn("Aprobado");
        modelo.addColumn("Anulado");
        modelo.addColumn("Finalizado");

        for (Object[] result : results) {
            // Se crea un array que será una de las filas de la tabla.
            Object[] fila; // Hay tres columnas en la tabla
            fila = result;
            // Se añade al modelo la fila completa.
            modelo.addRow(fila);
        }
        tblPruebas.setModel(modelo);
    }

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        String valor = txtValor.getText();
        String elemento = String.valueOf(cmbCampo.getSelectedItem());
        String campo = "";
        String condicion = "like";

        cJpaPruebas = new PruebasJpaController();
        switch (elemento) {
            case "Buscar Todos":
                cargarTabla();
                return;
            case "Nro de Documento":
                if (!CValidaciones.isNumeric(valor)) {
                    CMensajes.mensajeAdvertencia("Para Nro de Documento solo se aceptan números");
                    return;
                }
                campo = "p.carowner";
                condicion = "=";
                break;
            case "Placa":
                campo = "c.carplate";
                condicion = "=";
                break;
            case "Nro de Licencia":
                campo = "p.numerolicencia";
                valor += "%";
                break;
            case "Nombres":
                campo = "p.nombres";
                valor += "%";
                break;
            case "Apellidos":
                campo = "p.apellidos";
                valor += "%";
                break;
        }
        if (!CValidaciones.validarCampos(pnlConsulta)) {
            return;
        }
        results = cJpaPruebas.findHojasPrueba_porParametroCed(campo, valor, condicion);
        cargarTabla(results);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtValor.setText("");
        cmbCampo.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed


    private void tblPruebasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPruebasMouseClicked
//        int fila = tblPruebas.rowAtPoint(evt.getPoint());
//        int columna = 0;
//        int resultado = 0;
//        if ((fila > -1) && (columna > -1)) {
//            try {
//                resultado = Integer.parseInt(String.valueOf(modelo.getValueAt(fila, columna)));
//            } catch (Exception ex) {
//            }
//        }
//
//        try {
//            FrmPruebasDatos eda = new FrmPruebasDatos(resultado,0,this);
//            Principal1.desktop.add(eda);
//
//            eda.toFront();
//            eda.setMaximum(true);
//            eda.setVisible(true);
//            this.dispose();
//            this.setVisible(false);
//        } catch (Exception ex) {
//        }
        int fila = tblPruebas.rowAtPoint(evt.getPoint());
        int columna = 0;
        int resultado = 0;
        if ((fila > -1) && (columna > -1)) {
            try {
                resultado = Integer.parseInt(String.valueOf(modelo.getValueAt(fila, columna)));
            } catch (NumberFormatException ex) {
                LOG.severe(ex.getMessage());
                System.out.println("Error en cargue de modelo");
            }
        }

        try {
            FrmPruebasDatos eda = new FrmPruebasDatos(resultado, 0, this);
            Principal.desktop.add(eda);

            eda.toFront();
            eda.setMaximum(true);
            eda.setVisible(true);
            this.dispose();
            this.setVisible(false);
        } catch (PropertyVetoException ex) {
            LOG.severe(ex.getMessage());
            System.out.println("No ingreso a Hoja de Pruebas");
        }
    }//GEN-LAST:event_tblPruebasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cmbCampo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JTable tblPruebas;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
