/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrInt1.java
 *
 * Created on 30/06/2011, 11:05:09 AM
 */
package com.soltelec.servidor.igrafica;

import com.soltelec.servidor.model.TiposMedida;
import com.soltelec.servidor.dao.TiposMedidaJpaController;
import java.awt.Dimension;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SOLTELEC
 */
public class FrmTiposMedida extends javax.swing.JInternalFrame {

    JTable jTable1 = new javax.swing.JTable();
    JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    DefaultTableModel modelo;
    TiposMedida eJpaTiposMedida;
    TiposMedidaJpaController cJpaTiposMedida;
    static boolean editar;
    private static final Logger LOG = Logger.getLogger(FrmSimulacion.class.getName());

    /**
     * Creates new form FrInt1
     */
    public FrmTiposMedida() {

        super("Tipos de Medida",
                true, //resizable
                true, //closable
                false, //maximizable
                true);

//        Conexion.cargarConexion();
        initComponents();
        dimension();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedida = new javax.swing.JTable();

        setClosable(true);

        tblMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblMedida);
        cargarTabla();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1294, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dimension() {
        Dimension dim = super.getToolkit().getScreenSize();
        this.setSize(dim);
    }

    private void cargarTabla() {
        TiposMedidaJpaController mprop = new TiposMedidaJpaController();
        modelo = new DefaultTableModel();

        List<TiposMedida> results1 = mprop.findTMedida1();

        // Ahora sólo hay que rellenar el DefaultTableModel con los datos del ResultSet. La forma "manual" de hacer esto es la siguiente
        // Creamos las columnas.
        modelo.addColumn("Tipo Medida");
        modelo.addColumn("Tipo Prueba");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Unidad");

        for (TiposMedida results11 : results1) {
            // Se crea un array que será una de las filas de la tabla.
            Object[] fila = new Object[5]; // Hay tres columnas en la tabla
            // Se rellena cada posición del array con una de las columnas de la tabla en base de datos.
            fila[0] = results11.getMeasuretype();
            fila[1] = results11.getTesttype();
            fila[2] = results11.getNombremedida();
            fila[3] = results11.getDescripcionmedida();
            fila[4] = results11.getUnidad();
            // Se añade al modelo la fila completa.
            modelo.addRow(fila);
        }

        tblMedida.setModel(modelo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMedida;
    // End of variables declaration//GEN-END:variables
}
