/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.servidor.igrafica;

import com.soltelec.servidor.dao.LineasVehiculosJpaController;
import com.soltelec.servidor.dao.MarcasJpaController;
import com.soltelec.servidor.dao.exceptions.IllegalOrphanException;
import com.soltelec.servidor.dao.exceptions.NonexistentEntityException;
import com.soltelec.servidor.model.LineasVehiculos;
import com.soltelec.servidor.model.Marcas;
import com.soltelec.servidor.utils.CMensajes;
import com.soltelec.servidor.utils.CValidaciones;
import java.awt.HeadlessException;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class MarcasLineas extends javax.swing.JInternalFrame {

    private MarcasJpaController marca;
    private DefaultTableModel tableModel;
    private DefaultTableModel tableModelLinea;
    private LineasVehiculosJpaController lineasJpa;
    private Marcas marcas;
    private boolean editando = false;
    private int idMarcaPrincipal;
    private boolean esMarca = false;
    private int idLineaPrincipal;
    private Marcas marcaGlobal;
    private LineasVehiculos lineasVehiculosGlobal;
    private boolean editandoLinea;
    private static final Logger LOG = Logger.getLogger(FrmSimulacion.class.getName());

    /**
     * Creates new form MarcasLineas
     */
    public MarcasLineas() {
        initComponents();
        marca = new MarcasJpaController();
        lineasJpa = new LineasVehiculosJpaController();
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Clave");
        tableModel.addColumn("Marca");
        tableModelLinea = new DefaultTableModel();
        tableModelLinea.addColumn("Clave");
        tableModelLinea.addColumn("Linea");
        tableModelLinea.addColumn("Run");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        dialogo_buscar = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_marcas = new javax.swing.JTable();
        btn_aceptarBusqueda = new javax.swing.JButton();
        txt_buscquedas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dialogo_marca = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        txt_nombreProceso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_proceso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dialogo_linea = new javax.swing.JDialog();
        pnlLinea = new javax.swing.JPanel();
        btn_guardarLinea = new javax.swing.JButton();
        txt_nombreLinea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_run = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_eliminar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_lineas = new javax.swing.JTable();
        btn_nuevaLinea = new javax.swing.JButton();
        btn_nuevaMarca = new javax.swing.JButton();
        btn_buscar_marca = new javax.swing.JButton();
        labl_marca = new javax.swing.JLabel();
        btn_editarMarca = new javax.swing.JButton();
        btn_editarLinea = new javax.swing.JButton();
        btn_eliminarMarca = new javax.swing.JButton();
        btn_eliminarLinea = new javax.swing.JButton();

        dialogo_buscar.setMinimumSize(new java.awt.Dimension(520, 560));

        tabla_marcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_marcas);

        btn_aceptarBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/accept.png"))); // NOI18N
        btn_aceptarBusqueda.setText("Aceptar");
        btn_aceptarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarBusquedaActionPerformed(evt);
            }
        });

        txt_buscquedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscquedasActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/search.png"))); // NOI18N

        jLabel7.setText("Digite el nombre parcial o completo y presione enter.");

        javax.swing.GroupLayout dialogo_buscarLayout = new javax.swing.GroupLayout(dialogo_buscar.getContentPane());
        dialogo_buscar.getContentPane().setLayout(dialogo_buscarLayout);
        dialogo_buscarLayout.setHorizontalGroup(
            dialogo_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_buscarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(dialogo_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(dialogo_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_aceptarBusqueda)
                        .addGroup(dialogo_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(dialogo_buscarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_buscquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        dialogo_buscarLayout.setVerticalGroup(
            dialogo_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogo_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogo_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_buscquedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_aceptarBusqueda)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        dialogo_marca.setMinimumSize(new java.awt.Dimension(350, 150));
        dialogo_marca.setModal(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_nombreProceso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreProcesoKeyTyped(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre");

        btn_proceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/accept.png"))); // NOI18N
        btn_proceso.setText("Aceptar");
        btn_proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesoActionPerformed(evt);
            }
        });

        jLabel1.setText("Solo 20 caracteres");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_proceso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(txt_nombreProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );

        dialogo_marca.setSize(307, 150);

        javax.swing.GroupLayout dialogo_marcaLayout = new javax.swing.GroupLayout(dialogo_marca.getContentPane());
        dialogo_marca.getContentPane().setLayout(dialogo_marcaLayout);
        dialogo_marcaLayout.setHorizontalGroup(
            dialogo_marcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_marcaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogo_marcaLayout.setVerticalGroup(
            dialogo_marcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_marcaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_guardarLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/accept.png"))); // NOI18N
        btn_guardarLinea.setText("Aceptar");
        btn_guardarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarLineaActionPerformed(evt);
            }
        });

        txt_nombreLinea.setName("Nombre"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${lineasVehiculosGlobal.crlname}"), txt_nombreLinea, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel5.setText("Nombre");

        txt_run.setName("Run"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${lineasVehiculosGlobal.crlcod}"), txt_run, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel6.setText("Run");

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLineaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLineaLayout.createSequentialGroup()
                        .addComponent(btn_guardarLinea)
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addGroup(pnlLineaLayout.createSequentialGroup()
                        .addGroup(pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_run)
                            .addComponent(txt_nombreLinea))
                        .addContainerGap())))
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLineaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_nombreLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        dialogo_linea.setSize(340, 140);

        javax.swing.GroupLayout dialogo_lineaLayout = new javax.swing.GroupLayout(dialogo_linea.getContentPane());
        dialogo_linea.getContentPane().setLayout(dialogo_lineaLayout);
        dialogo_lineaLayout.setHorizontalGroup(
            dialogo_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_lineaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        dialogo_lineaLayout.setVerticalGroup(
            dialogo_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_lineaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images//trash24x24.png"))); // NOI18N
        btn_eliminar1.setText("Eliminar marca");

        setClosable(true);
        setIconifiable(true);
        setTitle("Marcas y lineas");

        table_lineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_lineas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_lineasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_lineas);

        btn_nuevaLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/new.png"))); // NOI18N
        btn_nuevaLinea.setText("Nueva linea");
        btn_nuevaLinea.setEnabled(false);
        btn_nuevaLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevaLineaActionPerformed(evt);
            }
        });

        btn_nuevaMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/new.png"))); // NOI18N
        btn_nuevaMarca.setText("Nueva marca");
        btn_nuevaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevaMarcaActionPerformed(evt);
            }
        });

        btn_buscar_marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/search.png"))); // NOI18N
        btn_buscar_marca.setText("Buscar marca");
        btn_buscar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_marcaActionPerformed(evt);
            }
        });

        labl_marca.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labl_marca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labl_marca.setText("Marca");

        btn_editarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/edit.png"))); // NOI18N
        btn_editarMarca.setText("Editar marca");
        btn_editarMarca.setEnabled(false);
        btn_editarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarMarcaActionPerformed(evt);
            }
        });

        btn_editarLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/edit.png"))); // NOI18N
        btn_editarLinea.setText("Editar linea");
        btn_editarLinea.setEnabled(false);
        btn_editarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarLineaActionPerformed(evt);
            }
        });

        btn_eliminarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/delete.png"))); // NOI18N
        btn_eliminarMarca.setText("Eliminar marca");
        btn_eliminarMarca.setEnabled(false);
        btn_eliminarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarMarcaActionPerformed(evt);
            }
        });

        btn_eliminarLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/delete.png"))); // NOI18N
        btn_eliminarLinea.setText("Eliminar linea");
        btn_eliminarLinea.setEnabled(false);
        btn_eliminarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarLineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_buscar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(labl_marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminarMarca)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_editarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_nuevaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_nuevaLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_editarLinea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminarLinea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(128, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labl_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_eliminarMarca))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_buscar_marca)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editarMarca)
                    .addComponent(btn_nuevaMarca)
                    .addComponent(btn_nuevaLinea)
                    .addComponent(btn_editarLinea)
                    .addComponent(btn_eliminarLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscquedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscquedasActionPerformed
        Object[] fila;
        String marcasBuscar = txt_buscquedas.getText();
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Clave");
        tableModel.addColumn("Marca");
        List<Marcas> listMarcas = marca.listarMarcas(marcasBuscar);
        if (!listMarcas.isEmpty()) {
            for (Marcas marcas1 : listMarcas) {
                fila = new Object[2];
                fila[0] = marcas1.getCarmark();
                fila[1] = marcas1.getNombremarca();
                tableModel.addRow(fila);
            }

        }
        tabla_marcas.setModel(tableModel);
    }//GEN-LAST:event_txt_buscquedasActionPerformed

    private void btn_aceptarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarBusquedaActionPerformed
        dialogo_buscar.setVisible(false);
        int fila = tabla_marcas.getSelectedRow();
        int columna = 0;

        if ((fila > -1) && (columna > -1)) {
            try {
                idMarcaPrincipal = Integer.parseInt(String.valueOf(tableModel.getValueAt(fila, columna)));
                String lablMarca = String.valueOf(tableModel.getValueAt(fila, 1));
                labl_marca.setText(lablMarca);
                cargarLineas();
                btn_editarMarca.setEnabled(true);
                btn_nuevaLinea.setEnabled(true);
                btn_eliminarMarca.setEnabled(true);
            } catch (Exception ex) {
                LOG.severe(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_aceptarBusquedaActionPerformed

    private void btn_buscar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_marcaActionPerformed
        dialogo_buscar.setVisible(true);
        dialogo_buscar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_buscar_marcaActionPerformed

    private void btn_nuevaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevaMarcaActionPerformed
        txt_nombreProceso.setText(null);
        editando = false;
        esMarca = true;
        dialogo_marca.setVisible(true);
        dialogo_marca.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_nuevaMarcaActionPerformed

    private void btn_procesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesoActionPerformed
        if (txt_nombreProceso.getText().length() > 20 || txt_nombreProceso.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Solo 20 caracteres y no puede estar vacio");
            return;
        }
        if (esMarca) {
            if (editando) {
                try {
                    MarcasJpaController marcasJpaController = new MarcasJpaController();
                    getMarcaGlobal().setNombremarca(txt_nombreProceso.getText());
                    marcasJpaController.edit(getMarcaGlobal());
                    labl_marca.setText(getMarcaGlobal().getNombremarca());
                    JOptionPane.showMessageDialog(this, "Se ha editado el registro");
                } catch (Exception ex) {
                    LOG.severe(ex.getMessage());
                    JOptionPane.showMessageDialog(this, "No se ha editado el registro " + ex);
                }
            } else {
                try {
                    MarcasJpaController marcasJpaController = new MarcasJpaController();
                    setMarcaGlobal(new Marcas());
                    getMarcaGlobal().setNombremarca(txt_nombreProceso.getText());
                    int idMarquita = marcasJpaController.ultimoIdMarca();
                    getMarcaGlobal().setCarmark(idMarquita + 1);
                    idMarcaPrincipal = getMarcaGlobal().getCarmark();
                    labl_marca.setText(getMarcaGlobal().getNombremarca());
                    cargarLineas();
                    marcasJpaController.create(getMarcaGlobal());
                    JOptionPane.showMessageDialog(this, "Se ha creado el registro");
                    btn_nuevaLinea.setEnabled(true);
                    btn_eliminarMarca.setEnabled(true);
                    btn_editarLinea.setEnabled(false);
                    btn_eliminarLinea.setEnabled(false);
                } catch (Exception ex) {
                    LOG.severe(ex.getMessage());
                    JOptionPane.showMessageDialog(this, "No se ha creado el registro " + ex);
                }
            }
        }
        dialogo_marca.setVisible(false);
    }//GEN-LAST:event_btn_procesoActionPerformed
    private void cargarLineas() {
        Object[] filaLinea;
        tableModelLinea = new DefaultTableModel();
        tableModelLinea.addColumn("Clave");
        tableModelLinea.addColumn("Linea");
        tableModelLinea.addColumn("Run");
        List<LineasVehiculos> listLineas = lineasJpa.buscarLineasPorMarca(idMarcaPrincipal);
        if (!listLineas.isEmpty()) {
            for (LineasVehiculos lineasVehiculos : listLineas) {
                filaLinea = new Object[3];
                filaLinea[0] = lineasVehiculos.getCarline();
                filaLinea[1] = lineasVehiculos.getCrlname();
                filaLinea[2] = lineasVehiculos.getCrlcod();
                tableModelLinea.addRow(filaLinea);
            }

        }
        table_lineas.setModel(tableModelLinea);
    }

    private void btn_editarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarMarcaActionPerformed
        MarcasJpaController marcasJpaController = new MarcasJpaController();
        setMarcaGlobal(marcasJpaController.findMarcas(idMarcaPrincipal));
        txt_nombreProceso.setText(getMarcaGlobal().getNombremarca());
        editando = true;
        esMarca = true;
        dialogo_marca.setLocationRelativeTo(null);
        dialogo_marca.setVisible(true);
    }//GEN-LAST:event_btn_editarMarcaActionPerformed

    private void table_lineasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_lineasMouseClicked
        try {
            int fila = table_lineas.rowAtPoint(evt.getPoint());
            if (fila > -1) {
                idLineaPrincipal = Integer.parseInt(tableModelLinea.getValueAt(fila, 0).toString());
                btn_editarLinea.setEnabled(true);
                btn_eliminarLinea.setEnabled(true);
            }
        } catch (NumberFormatException e) {
            LOG.severe(e.getMessage());
        }
    }//GEN-LAST:event_table_lineasMouseClicked

    private void btn_nuevaLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevaLineaActionPerformed
        txt_nombreLinea.setText(null);
        txt_run.setText(null);
        editandoLinea = false;
        dialogo_linea.setVisible(true);
        dialogo_linea.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_nuevaLineaActionPerformed

    private void btn_editarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarLineaActionPerformed
        LineasVehiculosJpaController lineasController = new LineasVehiculosJpaController();
        setLineasVehiculosGlobal(lineasController.findLineasVehiculos(idLineaPrincipal));
        txt_nombreLinea.setText(getLineasVehiculosGlobal().getCrlname());
        txt_run.setText(getLineasVehiculosGlobal().getCrlcod());
        editandoLinea = true;
        dialogo_linea.setVisible(true);
        dialogo_linea.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_editarLineaActionPerformed

    private void btn_eliminarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarMarcaActionPerformed
        int test = JOptionPane.showConfirmDialog(this, "Se va a eliminar el registro.");
        if (test != JOptionPane.OK_OPTION) {
            return;
        }

        try {
            MarcasJpaController marcasJpaController = new MarcasJpaController();
            marcasJpaController.destroy(idMarcaPrincipal);
            JOptionPane.showMessageDialog(this, "Se ha eliminado el registro ");
            labl_marca.setText(null);
            idMarcaPrincipal = -1;
            btn_editarMarca.setEnabled(false);
            btn_eliminarMarca.setEnabled(false);
            btn_editarLinea.setEnabled(false);
            btn_eliminarLinea.setEnabled(false);
            btn_nuevaLinea.setEnabled(false);
            cargarLineas();
        } catch (IllegalOrphanException | NonexistentEntityException | HeadlessException e) {
            LOG.severe(e.getMessage());
            JOptionPane.showMessageDialog(this, "No se ha eliminado el registro ya que esta referenciado en otro registro");
        }
    }//GEN-LAST:event_btn_eliminarMarcaActionPerformed

    private void btn_eliminarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarLineaActionPerformed
        int test = JOptionPane.showConfirmDialog(this, "Se va a eliminar el registro.");
        if (test != JOptionPane.OK_OPTION) {
            return;
        }
        try {
            LineasVehiculosJpaController lineasController = new LineasVehiculosJpaController();
            lineasController.destroy(idLineaPrincipal);
            JOptionPane.showMessageDialog(this, "Se ha eliminado el registro ");
            btn_editarLinea.setEnabled(false);
            btn_eliminarLinea.setEnabled(false);
            idLineaPrincipal = -1;
            cargarLineas();
        } catch (IllegalOrphanException | NonexistentEntityException | HeadlessException e) {
            LOG.severe(e.getMessage());
            JOptionPane.showMessageDialog(this, "No se ha eliminado el registro ya que esta referenciado en otro registro");
        }
    }//GEN-LAST:event_btn_eliminarLineaActionPerformed

    private void btn_guardarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarLineaActionPerformed
        if (editandoLinea) {
            try {
                if (!CValidaciones.validarCampos(pnlLinea)) {
                    return;
                }
                LineasVehiculosJpaController lineasController = new LineasVehiculosJpaController();
                getLineasVehiculosGlobal().setCrlname(txt_nombreLinea.getText());
                getLineasVehiculosGlobal().setCrlcod(txt_run.getText());
                lineasController.edit(getLineasVehiculosGlobal());
                JOptionPane.showMessageDialog(this, "Se ha editado el registro");
            } catch (Exception ex) {
                LOG.severe(ex.getMessage());
                JOptionPane.showMessageDialog(this, "No se ha editado el registro " + ex);
            }

        } else {
            LineasVehiculosJpaController lineasController = new LineasVehiculosJpaController();
            setLineasVehiculosGlobal(new LineasVehiculos());
            try {
                if (!CValidaciones.validarCampos(pnlLinea)) {
                    return;
                }
                getLineasVehiculosGlobal().setMarcas(new Marcas(idMarcaPrincipal));
                getLineasVehiculosGlobal().setCarline(lineasController.ultimoIdLinea() + 1);
                getLineasVehiculosGlobal().setCrlname(txt_nombreLinea.getText());
                getLineasVehiculosGlobal().setCrlcod(txt_run.getText());

                lineasController.create(getLineasVehiculosGlobal());
                CMensajes.mensajeCorrecto("Se ha creado el registro");
                CValidaciones.limpiarCampos(pnlLinea);
            } catch (Exception ex) {
                LOG.severe(ex.getMessage());
                CMensajes.mensajeError("No se ha creado el registro");
                CMensajes.mostrarExcepcion(ex);
            }
        }
        cargarLineas();
        btn_editarLinea.setEnabled(false);
        btn_eliminarLinea.setEnabled(false);
        dialogo_linea.setVisible(false);
    }//GEN-LAST:event_btn_guardarLineaActionPerformed

    private void txt_nombreProcesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreProcesoKeyTyped
        CValidaciones.limitarCaracteres(evt, txt_nombreProceso, 20);
    }//GEN-LAST:event_txt_nombreProcesoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptarBusqueda;
    private javax.swing.JButton btn_buscar_marca;
    private javax.swing.JButton btn_editarLinea;
    private javax.swing.JButton btn_editarMarca;
    private javax.swing.JButton btn_eliminar1;
    private javax.swing.JButton btn_eliminarLinea;
    private javax.swing.JButton btn_eliminarMarca;
    private javax.swing.JButton btn_guardarLinea;
    private javax.swing.JButton btn_nuevaLinea;
    private javax.swing.JButton btn_nuevaMarca;
    private javax.swing.JButton btn_proceso;
    private javax.swing.JDialog dialogo_buscar;
    private javax.swing.JDialog dialogo_linea;
    private javax.swing.JDialog dialogo_marca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labl_marca;
    private javax.swing.JPanel pnlLinea;
    private javax.swing.JTable tabla_marcas;
    private javax.swing.JTable table_lineas;
    private javax.swing.JTextField txt_buscquedas;
    private javax.swing.JTextField txt_nombreLinea;
    private javax.swing.JTextField txt_nombreProceso;
    private javax.swing.JTextField txt_run;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the marcaGlobal
     */
    public Marcas getMarcaGlobal() {
        return marcaGlobal;
    }

    /**
     * @param marcaGlobal the marcaGlobal to set
     */
    public void setMarcaGlobal(Marcas marcaGlobal) {
        this.marcaGlobal = marcaGlobal;
    }

    /**
     * @return the lineasVehiculosGlobal
     */
    public LineasVehiculos getLineasVehiculosGlobal() {
        return lineasVehiculosGlobal;
    }

    /**
     * @param lineasVehiculosGlobal the lineasVehiculosGlobal to set
     */
    public void setLineasVehiculosGlobal(LineasVehiculos lineasVehiculosGlobal) {
        this.lineasVehiculosGlobal = lineasVehiculosGlobal;
    }
}
