/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.servidor.igrafica;

import com.soltelec.servidor.dao.PruebasJpaController;
import com.soltelec.servidor.model.EstadoPruebas;
import com.soltelec.servidor.model.Medidas;
import com.soltelec.servidor.model.Pruebas;
import com.soltelec.servidor.model.Vehiculos;
import com.soltelec.servidor.utils.GenericExportExcel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dany
 */
public class ReporteOnacM extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloDatos;

    /**
     * Creates new form ReporteOnacM
     */
    public ReporteOnacM() {
        initComponents();
        iniciarModelo();
    }

    private void iniciarModelo() {
        modeloDatos = new DefaultTableModel();
        modeloDatos.addColumn("Placa");
        //modeloDatos.addColumn("Hoja Prueba");
        modeloDatos.addColumn("Marca");
        modeloDatos.addColumn("Linea");
        modeloDatos.addColumn("Modelo");
        modeloDatos.addColumn("Cilindraje");
        modeloDatos.addColumn("Peso Eje Delantero");
        modeloDatos.addColumn("Peso Eje Trasero");
        modeloDatos.addColumn("Fuerza Eje Delantero");
        modeloDatos.addColumn("Fuerza Eje Trasero");
        modeloDatos.addColumn("Eficacia");
        modeloDatos.addColumn("Estado");
    }

    private void fillData(Date fInicial, Date fFinal) {
        iniciarModelo();
        SimpleDateFormat smf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        List<Pruebas> pruebas = new PruebasJpaController().reporteMotosOnacMedellin(fInicial, fFinal);
        Object[] datos = new Object[modeloDatos.getColumnCount()];

        for (Pruebas prueba : pruebas) {
            int i = 0;
            Vehiculos vehiculo = prueba.getHojaPruebas().getVehiculos();
            datos[0] = vehiculo.getCarplate();
            //datos[1] = prueba.getHojaPruebas().getTestsheet();
            datos[1] = vehiculo.getMarcas().getNombremarca();
            datos[2] = vehiculo.getLineasVehiculos().getCrlname();
            datos[3] = vehiculo.getModelo();
            datos[4] = vehiculo.getCilindraje();

            for (Medidas medida : prueba.getMedidasList()) {
                switch (medida.getTiposMedida().getMeasuretype()) {
                    case 5000: //Peso Delantero
                        datos[5] = medida.getValormedida();
                        break;
                    case 5001: //Peso Trasero
                        datos[6] = medida.getValormedida();
                        break;
                    case 5008: //Fuerza Delantera
                        datos[7] = medida.getValormedida();
                        break;
                    case 5009: //Fuerza Trasera
                        datos[8] = medida.getValormedida();
                        break;
                    case 5024: //Eficacia
                        datos[9] = medida.getValormedida();
                        break;
                }
            }
            
            EstadoPruebas estadoPruebas;
            
            if (prueba.getAbortada().equals("Y")) {
                estadoPruebas = EstadoPruebas.ANULADA;
            } else if (prueba.getFinalizada().equals("Y")) {
                estadoPruebas = (prueba.getAprobada().equals("Y") ? EstadoPruebas.APROBADA : EstadoPruebas.REPROBADA);
            } else {
                estadoPruebas = EstadoPruebas.PENDIENTE;
            }

            datos[10] = estadoPruebas;
            
            modeloDatos.addRow(datos);
        }

        tblDatos.setModel(modeloDatos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dteInicio = new org.jdesktop.swingx.JXDatePicker();
        dteInicio.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        jLabel2 = new javax.swing.JLabel();
        dteFin = new org.jdesktop.swingx.JXDatePicker();
        dteFin.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        btnGenerar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jLabel1.setText("Fecha Inicio:");

        jLabel2.setText("Fecha Fin:");

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/green_flag.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/save.png"))); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDatos.setName("Reporte"); // NOI18N
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dteInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dteFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExportar)
                .addContainerGap(223, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dteInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(dteFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnGenerar)
                    .addComponent(btnExportar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
        );

        setBounds(0, 0, 816, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        if (dteInicio.getDate() == null || dteFin.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione Fechas");
            return;
        }

        fillData(dteInicio.getDate(), dteFin.getDate());
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        GenericExportExcel excel = new GenericExportExcel();
        excel.exportExcel(tblDatos);
    }//GEN-LAST:event_btnExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteOnacM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteOnacM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteOnacM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteOnacM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ReporteOnacM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGenerar;
    private org.jdesktop.swingx.JXDatePicker dteFin;
    private org.jdesktop.swingx.JXDatePicker dteInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables

}
