/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.servidor.igrafica;

import com.soltelec.servidor.dao.VehiculosJpaController;
import com.soltelec.servidor.model.NativoVehiculosSuperIntendencia;
import com.soltelec.servidor.utils.GenericExportExcel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Berna Reporte generado para la super intendencia
 * @Requerimiento DT-5
 *
 */
public class ReporteSuperIntendencia extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;

    public ReporteSuperIntendencia() {
        super("Reporte Super intendencia",
                true, //resizable
                true, //closable
                false, //maximizable
                true);
        initModels();
        initComponents();

    }

    private void initModels() {
        // ***** MODELO PARA LAS PRUEBA LUCES *****
        modelo = new DefaultTableModel();
        modelo.addColumn("No"); //0
        modelo.addColumn("PLACA"); //1
        modelo.addColumn("MARCA");//2
        modelo.addColumn("MODELO");//3
        modelo.addColumn("PARTICULAR");//4
        modelo.addColumn("PUBLICO");//5
        modelo.addColumn("MOTOS");//6
        modelo.addColumn("AUTOMOVIL");//7
        modelo.addColumn("CAMPERO");//8
        modelo.addColumn("CAMIONETA");//9
        modelo.addColumn("MICROBUS");//10
        modelo.addColumn("BUS");//11
        modelo.addColumn("BUSETA");//12
        modelo.addColumn("CAMION");//13
        modelo.addColumn("VOLQUETA");//14
        modelo.addColumn("TRACTO CAMION");//15
        modelo.addColumn("R");//16
        modelo.addColumn("A");//17
        modelo.addColumn("1°");//18
        modelo.addColumn("2°");//19
        modelo.addColumn("3°");//20
        modelo.addColumn("No CERTIFICADO DE APROBACIÓN");//21
        modelo.addColumn("OBSERVACIONES");//22
        modelo.addColumn("FECHA");//23

    }

    private void fillData(Date fechaInicial, Date fechaFinal) {
        initModels();
        Object[] modeloRow = new Object[24]; // Hay 25 columnas en la tabla

        VehiculosJpaController jpaController = new VehiculosJpaController();
        List<NativoVehiculosSuperIntendencia> datos = jpaController.findNativoVehiculos(fechaInicial, fechaFinal);

        if (datos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay datos para el rango de fechas");
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (NativoVehiculosSuperIntendencia nvsi : datos) {
            modeloRow[0] = nvsi.getId();
            modeloRow[1] = nvsi.getPlaca();
            modeloRow[2] = nvsi.getMarca();
            modeloRow[3] = nvsi.getModelo();
            modeloRow[4] = nvsi.getParticular();
            modeloRow[5] = nvsi.getPublico();
            modeloRow[6] = nvsi.getMotos();
            modeloRow[7] = nvsi.getAutomovil();
            modeloRow[8] = nvsi.getCampero();
            modeloRow[9] = nvsi.getCamioneta();
            modeloRow[10] = nvsi.getMicrobus();
            modeloRow[11] = nvsi.getBus();
            modeloRow[12] = nvsi.getBuseta();
            modeloRow[13] = nvsi.getCamion();
            modeloRow[14] = nvsi.getVolqueta();
            modeloRow[15] = nvsi.getTractoCamion();
            modeloRow[16] = nvsi.getR();
            modeloRow[17] = nvsi.getA();
            modeloRow[18] = nvsi.getUno();
            modeloRow[19] = nvsi.getDos();
            modeloRow[20] = nvsi.getTres();
            modeloRow[21] = nvsi.getNoCertificado();
            modeloRow[22] = nvsi.getObservaciones();
            modeloRow[23] = sdf.format(nvsi.getFecha());
            modelo.addRow(modeloRow);
        }

        tblLuces.setModel(modelo);
        tblLuces.setEnabled(false);
    } //end filldata

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dteInicio = new org.jdesktop.swingx.JXDatePicker();
        dteInicio.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        dteFin = new org.jdesktop.swingx.JXDatePicker();
        dteInicio.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        btnGenerar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLuces = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1024, 768));

        jLabel1.setText("Fecha Inicio:");

        jLabel2.setText("Fecha Fin:");

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/search.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/servidor/images/save.png"))); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        tblLuces.setModel(modelo);
        tblLuces.setName("Luces"); // NOI18N
        jScrollPane1.setViewportView(tblLuces);

        jTabbedPane1.addTab("Reporte superintendencia", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dteInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dteFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExportar)
                .addContainerGap(224, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(dteInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dteFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar)
                    .addComponent(btnExportar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
        );

        setBounds(0, 0, 816, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if (dteInicio.getDate() == null || dteFin.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione Fechas");
            return;
        }
        SwingUtilities.invokeLater(
                new Runnable() {

            @Override
            public void run() {
                fillData(dteInicio.getDate(), dteFin.getDate());
            }
        });
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        List<JTable> tables = new ArrayList<>();
        tables.add(tblLuces);
        GenericExportExcel excel = new GenericExportExcel();
        excel.exportExcel(tables);
    }//GEN-LAST:event_btnExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGenerar;
    private org.jdesktop.swingx.JXDatePicker dteFin;
    private org.jdesktop.swingx.JXDatePicker dteInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblLuces;
    // End of variables declaration//GEN-END:variables
}
