package com.soltelec.servidor.dtos.reporte_corponor;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Corponor {
    private String 
    fechaInicio,
    fechaFin,
    municipio,
    lugar,
    nFur,
    nCertificado,
    serialAnalizador,
    pef,
    marcaSoftware,
    versionSoftware,
    idInspector,
    placa,
    marcaCarro,
    modeloCarro,
    cilindraje,
    linea,
    clase,
    servicio,
    tCombustible,
    tMotor,
    nExostos,
    design,
    tempAmbiente,
    humedadRelativa,
    ltoe,
    metodoMedicionTemp,
    tempMotor,
    tempFinal,
    rpmRalenti,
    rpmCruceroOGobernada,
    hcRalenti,
    hcCrucero,
    coRalenti,
    coCrucero,
    co2Ralenti,
    co2Crucero,
    o2Ralenti,
    o2Crucero,
    cicloPreliminar,
    rpmGobernadaCicloPreliminar,
    rpmRalentiCicloPreliminar,
    opacidadC1,
    gobernadaC1,
    ralentiC1,
    opacidadC2,
    gobernadaC2,
    ralentiC2,
    opacidadC3,
    gobernadaC3,
    ralentiC3,
    promedioFinal,
    mCPreliminar,
    mc1,
    mc2,
    mc3,
    mPromedioFinal,
    conceptoFinal,
    presenciaHumo,
    dilucionMezcla,
    nivelEmisiones,
    rpmFueraRango,
    fugasTubo,
    salidasAdicionales,
    tapaAceite,
    tapaCombustible,
    filtroAire,
    accesorios,
    incorrectaRefrigeracion,
    emisiones, 
    incorrectaOperacionGobernador,
    fallaSubita,
    ejecucionIncorrecta,
    diferenciaAritmetica,
    diferenciaTemperatura,
    instalacionTubo,
    filtroAire2,
    fallaEquipoMedicion,
    fallaFluidoElectrico,
    bloqueoForzadoEquipoMedicion,
    ejecucionIncorrectaPrueba,
    fallaDesviacionCero,
    resolucionAplicada,
    ruidos,
    dispositivos;

}
